version: '3.8'

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile.node
        image: my-vue-node
        container_name: my-vue-node
        ports:
            - "5173:5173"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
